#!/bin/sh

unset SESSION_MANAGER
vncconfig -nowin &
xsetroot -solid black

while true; do
    "$HOME/.builds/dwm-6.1/bin/dwm" &
    xsetroot -name "$(date +"%A %Y-%m-%d %H:%M:%S")$("$HOME/bin/cpu")"
    sleep 1
done

# end of file
